export const UPGRADE_TREES = {
    RHIZOME: {
        id: 'RHIZOME',
        name: 'The Flesh (Rhizome)',
        color: '#FF69B4', // Plumbus Pink
        nodes: [
            {
                id: 'mycelial_network',
                name: 'Mycelial Network',
                description: 'Unlock the ability to build nodes.',
                cost: { stardust: 0 },
                position: { x: 50, y: 90 },
                unlockedByDefault: true,
            },
            {
                id: 'rapid_expansion',
                name: 'Basic Membrane Stretching',
                description: 'Nodes cost 5% less Stardust.',
                cost: { lucidity: 1 },
                parentId: 'mycelial_network',
                position: { x: 50, y: 80 },
            },
            {
                id: 'spore_velocity',
                name: 'Spore Velocity I',
                description: 'Hyphae grow animation is 10% faster.',
                cost: { lucidity: 2 },
                parentId: 'rapid_expansion',
                position: { x: 40, y: 70 },
            },
            {
                id: 'duct_tape',
                name: 'Duct Tape Reinforcement',
                description: 'Increases max connection length by 15%.',
                cost: { lucidity: 3 },
                parentId: 'rapid_expansion',
                position: { x: 60, y: 70 },
            },
            {
                id: 'mitosis_lottery',
                name: 'Mitosis Lottery',
                description: '1% chance a built node is free.',
                cost: { lucidity: 5 },
                parentId: 'spore_velocity',
                position: { x: 30, y: 60 },
            },
            {
                id: 'scavenger_enzymes',
                name: 'Scavenger Enzymes',
                description: 'Connecting to trash yields double Stardust.',
                cost: { lucidity: 5 },
                parentId: 'duct_tape',
                position: { x: 70, y: 60 },
                permit: 'solid_waste',
            },
            // ...
            {
                id: 'high_pressure_pumps',
                name: 'High-Pressure Pumps',
                description: 'Source Node generates +10% Pressure.',
                cost: { lucidity: 3 },
                parentId: 'wider_valves',
                position: { x: 60, y: 80 },
                permit: 'high_voltage',
            },
            // ...
            {
                id: 'fourth_wall_break',
                name: 'Fourth Wall Break',
                description: 'The Bureaucrats insult you personally. +20% Lucidity.',
                cost: { lucidity: 60 },
                parentId: 'mirror_dimension',
                position: { x: 20, y: 40 },
                permit: 'existential_compliance',
            },
            {
                id: 'auto_seeker',
                name: 'Auto-Seeker Tendrils',
                description: 'Automatically grows to nearest prism every 10s.',
                cost: { lucidity: 10 },
                parentId: 'mitosis_lottery',
                position: { x: 20, y: 50 },
            },
            {
                id: 'recycled_veins',
                name: 'Recycled Veins',
                description: 'Deleting a node refunds 80% Stardust.',
                cost: { lucidity: 8 },
                parentId: 'scavenger_enzymes',
                position: { x: 80, y: 50 },
            },
            {
                id: 'fractal_branching',
                name: 'Fractal Branching',
                description: 'Every 10th node spawns two free mini-hyphae.',
                cost: { lucidity: 15 },
                parentId: 'auto_seeker',
                position: { x: 30, y: 40 },
            },
            {
                id: 'hyper_tesselation',
                name: 'Hyper-Tesselation',
                description: 'Nodes automatically align to a hexagonal grid.',
                cost: { lucidity: 20 },
                parentId: 'recycled_veins',
                position: { x: 70, y: 40 },
            },
            {
                id: 'spore_velocity_2',
                name: 'Spore Velocity II',
                description: 'Hyphae grow animation is 25% faster.',
                cost: { lucidity: 25 },
                parentId: 'fractal_branching',
                position: { x: 40, y: 30 },
            },
            {
                id: 'auto_mandala',
                name: 'Auto-Mandala',
                description: 'Automatically builds symmetrical patterns around your Source Node.',
                cost: { lucidity: 50 },
                parentId: 'hyper_tesselation',
                position: { x: 60, y: 30 },
            },
            {
                id: 'spore_velocity_3',
                name: 'Spore Velocity III',
                description: 'Growth is instant.',
                cost: { lucidity: 100 },
                parentId: 'spore_velocity_2',
                position: { x: 50, y: 10 },
            },
            {
                id: 'the_great_blob',
                name: 'The Great Blob',
                description: 'All nodes visually merge into one giant throbbing mass.',
                cost: { lucidity: 200 },
                parentId: 'spore_velocity_3',
                position: { x: 50, y: 0 },
            }
        ]
    },
    METABOLISM: {
        id: 'METABOLISM',
        name: 'The Juice (Metabolism)',
        color: '#00FF00', // Portal Green
        nodes: [
            {
                id: 'wider_valves',
                name: 'Wider Valves',
                description: 'Base pipe width +10%.',
                cost: { lucidity: 1 },
                parentId: 'mycelial_network', // Root dependency
                position: { x: 50, y: 90 },
            },
            {
                id: 'greased_pipes',
                name: 'Greased Pipes',
                description: 'Fluid drag reduced by 5%.',
                cost: { lucidity: 2 },
                parentId: 'wider_valves',
                position: { x: 40, y: 80 },
            },
            {
                id: 'high_pressure_pumps',
                name: 'High-Pressure Pumps',
                description: 'Source Node generates +10% Pressure.',
                cost: { lucidity: 3 },
                parentId: 'wider_valves',
                position: { x: 60, y: 80 },
            },
            {
                id: 'mercury_blood',
                name: 'Mercury Blood',
                description: 'Fluid has -10% viscosity.',
                cost: { lucidity: 5 },
                parentId: 'greased_pipes',
                position: { x: 30, y: 70 },
            },
            {
                id: 'osmotic_surge',
                name: 'Osmotic Surge',
                description: 'Passive Flow Rate +5%.',
                cost: { lucidity: 5 },
                parentId: 'high_pressure_pumps',
                position: { x: 70, y: 70 },
            },
            {
                id: 'nutrient_compression',
                name: 'Nutrient Compression',
                description: 'Nodes can store 2x Stardust.',
                cost: { lucidity: 8 },
                parentId: 'mercury_blood',
                position: { x: 20, y: 60 },
            },
            {
                id: 'super_conductive_sap',
                name: 'Super-Conductive Sap',
                description: 'Reduces resistance penalties for long-distance pipes.',
                cost: { lucidity: 10 },
                parentId: 'osmotic_surge',
                position: { x: 80, y: 60 },
            },
            {
                id: 'synesthetic_resonance',
                name: 'Synesthetic Resonance',
                description: 'The louder the music, the faster the flow.',
                cost: { lucidity: 15 },
                parentId: 'nutrient_compression',
                position: { x: 30, y: 50 },
            },
            {
                id: 'overclocked_hearts',
                name: 'Overclocked Hearts',
                description: 'Relay Nodes now pump pressure.',
                cost: { lucidity: 20 },
                parentId: 'super_conductive_sap',
                position: { x: 70, y: 50 },
            },
            {
                id: 'turbulent_flow',
                name: 'Turbulent Flow',
                description: 'High pressure generates extra Flux (at risk of pipe bursting).',
                cost: { lucidity: 25 },
                parentId: 'overclocked_hearts',
                position: { x: 60, y: 40 },
            },
            {
                id: 'zero_point_energy',
                name: 'Zero-Point Energy',
                description: 'Idle nodes generate 1% Flux/sec.',
                cost: { lucidity: 30 },
                parentId: 'synesthetic_resonance',
                position: { x: 40, y: 40 },
            },
            {
                id: 'flux_capacitor',
                name: 'Flux Capacitor',
                description: 'Unlocks "Time Travel" (Offline Progress is 2x effective).',
                cost: { lucidity: 50 },
                parentId: 'zero_point_energy',
                position: { x: 50, y: 20 },
            },
            {
                id: 'dark_matter_injection',
                name: 'Dark Matter Injection',
                description: 'Flow rate +100%, but visual stability decreases.',
                cost: { lucidity: 100 },
                parentId: 'flux_capacitor',
                position: { x: 50, y: 10 },
                permit: 'high_voltage',
            }
        ]
    },

    HALLUCINATION: {
        id: 'HALLUCINATION',
        name: 'The Trip (Hallucination)',
        color: '#9400D3', // Lucidity Purple
        nodes: [
            {
                id: 'third_eye_squeegee',
                name: 'Third Eye Squeegee',
                description: 'Clears fog in a small radius on click.',
                cost: { lucidity: 5 },
                parentId: 'mycelial_network',
                position: { x: 50, y: 90 },
            },
            {
                id: 'lucky_glitch',
                name: 'Lucky Glitch',
                description: '5% chance for a Prism to be "Shiny" (10x value).',
                cost: { lucidity: 10 },
                parentId: 'third_eye_squeegee',
                position: { x: 40, y: 80 },
            },
            {
                id: 'drop_the_bass',
                name: 'Drop the Bass',
                description: 'Active Skill: Shockwave clears all fog.',
                cost: { lucidity: 15 },
                parentId: 'third_eye_squeegee',
                position: { x: 60, y: 80 },
            },
            {
                id: 'ego_death',
                name: 'Ego Death',
                description: 'Passive: UI dissolves, production triples.',
                cost: { lucidity: 20 },
                parentId: 'lucky_glitch',
                position: { x: 30, y: 70 },
            },
            {
                id: 'glitch_the_matrix',
                name: 'Glitch the Matrix',
                description: 'Active Skill: Re-roll resource types of all Prisms.',
                cost: { lucidity: 25 },
                parentId: 'drop_the_bass',
                position: { x: 70, y: 70 },
            },
            {
                id: 'karma_farming',
                name: 'Karma Farming',
                description: 'Passive: Clicking nothing generates small amounts of Flux.',
                cost: { lucidity: 30 },
                parentId: 'ego_death',
                position: { x: 20, y: 60 },
            },
            {
                id: 'schrodingers_cat',
                name: 'Schrodinger’s Cat',
                description: 'Prisms are both Empty and Full until connected.',
                cost: { lucidity: 40 },
                parentId: 'glitch_the_matrix',
                position: { x: 80, y: 60 },
            },
            {
                id: 'mirror_dimension',
                name: 'Mirror Dimension',
                description: 'Active Skill: Double all output for 60s.',
                cost: { lucidity: 50 },
                parentId: 'karma_farming',
                position: { x: 30, y: 50 },
            },
            {
                id: 'fourth_wall_break',
                name: 'Fourth Wall Break',
                description: 'The Bureaucrats insult you personally. +20% Lucidity.',
                cost: { lucidity: 60 },
                parentId: 'mirror_dimension',
                position: { x: 20, y: 40 },
            },
            {
                id: 'time_dilation',
                name: 'Time Dilation',
                description: 'Slows down simulation but increases precision (Flux gen).',
                cost: { lucidity: 70 },
                parentId: 'fourth_wall_break',
                position: { x: 30, y: 30 },
            },
            {
                id: 'kaleidoscope_eyes',
                name: 'Kaleidoscope Eyes',
                description: 'Visuals fracture. Unlocks "Split Screen" mode (Cosmetic).',
                cost: { lucidity: 80 },
                parentId: 'time_dilation',
                position: { x: 40, y: 20 },
            },
            {
                id: 'color_shift',
                name: 'Color Shift',
                description: 'The world cycles through the spectrum.',
                cost: { lucidity: 90 },
                parentId: 'kaleidoscope_eyes',
                position: { x: 50, y: 30 },
            },
            {
                id: 'simulation_hypothesis',
                name: 'Simulation Hypothesis',
                description: 'Reveals the code behind the world.',
                cost: { lucidity: 150 },
                parentId: 'dev_console',
                position: { x: 80, y: 40 },
            },
            {
                id: 'infinite_improbability',
                name: 'Infinite Improbability',
                description: 'Random things happen randomly.',
                cost: { lucidity: 300 },
                parentId: 'simulation_hypothesis',
                position: { x: 90, y: 30 },
            },
            {
                id: 'polymorph',
                name: 'Polymorph',
                description: 'Clicking Enemies turns them into Wisps.',
                cost: { lucidity: 45 },
                parentId: 'schrodingers_cat',
                position: { x: 90, y: 50 },
            },
            {
                id: 'dmt_elf_pact',
                name: 'DMT Elf Pact',
                description: 'Machine Elves build nodes for you.',
                cost: { lucidity: 111 },
                parentId: 'polymorph',
                position: { x: 80, y: 20 },
            },
            {
                id: 'save_scumming',
                name: 'Save Scumming',
                description: 'Active Skill: Restore resources to a previous state.',
                cost: { lucidity: 120 },
                parentId: 'dmt_elf_pact',
                position: { x: 70, y: 10 },
            },
            {
                id: 'god_mode',
                name: 'God Mode',
                description: 'Active Skill: 10s of infinite resources. 1 hour cooldown.',
                cost: { lucidity: 500 },
                parentId: 'dev_console',
                position: { x: 60, y: 20 },
            },
            {
                id: 'the_red_pill',
                name: 'The Red Pill',
                description: 'Hard Reset. Wipes everything. Wake up.',
                cost: { lucidity: 1000 },
                parentId: 'god_mode',
                position: { x: 40, y: 10 },
            },
            {
                id: 'ascended_glitch',
                name: 'Ascended Glitch',
                description: 'Triggers a fatal system error. You win?',
                cost: { lucidity: 1337 },
                parentId: 'god_mode',
                position: { x: 60, y: 10 },
            }
        ]
    }
};

// Add missing nodes to other trees
UPGRADE_TREES.RHIZOME.nodes.push(
    {
        id: 'wall_clinging',
        name: 'Wall Clinging',
        description: 'Building near rocks costs 50% less.',
        cost: { lucidity: 12 },
        parentId: 'scavenger_enzymes',
        position: { x: 80, y: 70 },
    },
    {
        id: 'void_anchors',
        name: 'Void Anchors',
        description: 'Double max connection length.',
        cost: { lucidity: 18 },
        parentId: 'wall_clinging',
        position: { x: 90, y: 60 },
    },
    {
        id: 'parasitic_embedding',
        name: 'Parasitic Embedding',
        description: 'Allows building nodes INSIDE enemies.',
        cost: { lucidity: 30 },
        parentId: 'auto_seeker',
        position: { x: 10, y: 40 },
    },
    {
        id: 'cosmic_composting',
        name: 'Cosmic Composting',
        description: 'Enemies die when built inside, yielding Stardust.',
        cost: { lucidity: 40 },
        parentId: 'parasitic_embedding',
        position: { x: 10, y: 30 },
    },
    {
        id: 'bio_luminescence',
        name: 'Bio-Luminescence',
        description: 'Nodes clear Fog of War.',
        cost: { lucidity: 50 },
        parentId: 'cosmic_composting',
        position: { x: 20, y: 20 },
    }
);

UPGRADE_TREES.METABOLISM.nodes.push(
    {
        id: 'plumbus_coating',
        name: 'Plumbus Coating',
        description: 'Significantly reduced friction.',
        cost: { lucidity: 12 },
        parentId: 'greased_pipes',
        position: { x: 20, y: 80 },
    },
    {
        id: 'reverse_osmosis',
        name: 'Reverse Osmosis',
        description: 'Flow against pressure is easier.',
        cost: { lucidity: 18 },
        parentId: 'plumbus_coating',
        position: { x: 10, y: 70 },
    },
    {
        id: 'leak_plugging',
        name: 'Leak Plugging',
        description: 'Passive Stardust generation.',
        cost: { lucidity: 22 },
        parentId: 'reverse_osmosis',
        position: { x: 10, y: 60 },
    },
    {
        id: 'alchemical_fire',
        name: 'Alchemical Fire',
        description: 'Burn excess Stardust into Flux.',
        cost: { lucidity: 35 },
        parentId: 'leak_plugging',
        position: { x: 10, y: 50 },
    },
    {
        id: 'sentient_fluid',
        name: 'Sentient Fluid',
        description: 'Fluid auto-balances pressure.',
        cost: { lucidity: 60 },
        parentId: 'turbulent_flow',
        position: { x: 70, y: 30 },
    },
    {
        id: 'interdimensional_plumbing',
        name: 'Interdimensional Plumbing',
        description: 'Pressure teleports between nodes.',
        cost: { lucidity: 80 },
        parentId: 'sentient_fluid',
        position: { x: 80, y: 20 },
    },
    {
        id: 'singularity_core',
        name: 'Singularity Core',
        description: 'Passive Lucidity generation.',
        cost: { lucidity: 90 },
        parentId: 'interdimensional_plumbing',
        position: { x: 90, y: 10 },
    },
    {
        id: 'universal_solvent',
        name: 'Universal Solvent',
        description: 'Click rocks to destroy them.',
        cost: { lucidity: 100 },
        parentId: 'singularity_core',
        position: { x: 80, y: 0 },
    }
);

export const getAllUpgrades = () => {
    const all = [];
    Object.values(UPGRADE_TREES).forEach(tree => {
        all.push(...tree.nodes);
    });
    return all;
};
