import React, { useState, useEffect } from 'react';
import SquishyButton from './SquishyButton';
import { useCRTWindow } from '../hooks/useCRTWindow';

const README_CONTENT = `# NEON MYCELIUM

> "It's not a bug, it's a feature. And that feature is a tumor named Gary."

> **WARNING:** **AUDIO SAFETY & CONTROLS**
> *   **Settings:** The **Angry Valve** (Top Left) opens the Settings menu.
> *   **Volume:** Game sounds can be overwhelming! It is recommended to turn them down immediately.
> *   **Radio:** The **Radio Widget** (Bottom Right) is independent of Master Volume. Try the **North Korean Station** for maximum vibes.

Neon Mycelium is a psychedelic, idle-incremental strategy game about managing a cosmic fungal network, dealing with bureaucratic nightmares, and enduring the constant mockery of your own UI.

## 🌟 Core Features

### The Network
*   **Procedural Node Generation:** Grow your mycelial network across an infinite void.
*   **Fluid Simulation:** Resources (Stardust, Flux, Lucidity) flow through connections like liquid.
*   **Infinite Zoom:** Scroll forever. The universe is fractal.
*   **Dimensional Shifts:** Unlock new dimensions (Mirror Realm, Glitch Dimension) that alter physics and visuals.

> [!TIP]
> **PRO TIP:** Drag from one node to another to create connections! This allows resources to flow and kickstarts your economy.

### The Economy
*   **Stardust:** The raw matter of the universe. Used to build nodes.
*   **Flux:** The energy of connection. Generated by flow.
*   **Lucidity:** The currency of awareness. Used for upgrades and dealing with... things.
*   **Sunk Cost Pit:** A literal bottomless pit where you can throw your resources away for absolutely no reward. (Now emoji-free!)

## 🤡 The "Silly" Addons (Module F & Beyond)

This game is packed with "features" designed to troll, confuse, or mildly inconvenience you.

### UI & Interaction
*   **Gary the Tumor:** Your sentient, sarcastic AI companion who hates you. He pulses, he grumbles, he judges your APM.
*   **Banana for Scale:** A photorealistic banana that floats across the screen. Hover over objects to see their size in Bananas (to 5 decimal places!).
*   **Squishy Buttons:** Every button wobbles, bounces, or resists being clicked.
*   **Smart Cursor:** A cursor that gets bored, wanders off, or actively avoids the button you're trying to click.
*   **Winamp Visualizer:** A fully functional, nostalgic audio visualizer that reacts to the game's soundtrack.
*   **TOS Monolith:** A massive, scrolling Terms of Service agreement that physically blocks your view until you "agree" (or destroy it).
*   **Captcha Checkpoint:** Randomly asks you to prove you aren't a robot by solving impossible philosophical questions.
*   **Copyright Strike:** A fake legal overlay that claims you've infringed on "The Concept of Circles."
*   **Heat Death Countdown:** A timer counting down to the end of the universe. Don't worry, it's very long.

### Entities & Encounters
*   **Hate Mail:** Receive angry letters from microscopic civilizations you accidentally crushed.
*   **Generic NPCs:** Untextured, grey humanoids that wander the void, T-posing and muttering Skyrim quotes.
*   **Emotional Baggage:** Literal suitcases that drift by. If you don't repress them, they make you sad.
*   **Schrödinger's Catbox:** A vibrating box. Is the cat alive? Dead? Both? Click to find out (and maybe explode).
*   **Spaghetti Code Tangles:** Glitchy masses of neon wire that scramble your resource packets.
*   **Wet Floor Zones:** Yellow caution areas that muffle all game audio to an underwater "glug-glug" sound.
*   **Time Traveler's Regret:** Paradox entities that try to delete your source node to prevent their own creation.
*   **Sentient Mold Neighbor:** A neighbor who borrows your sugar (Flux) and never returns it.
*   **Paid Promotion Blimp:** A giant blimp advertising fake products like "Gluten-Free Dark Matter."

### Systems & Mechanics
*   **Bureaucracy Mode:** Fill out tax forms (Form 27B-6) to legalize your illegal node placements.
*   **Cheat Cartridges:** Physical NES-style cartridges you have to "blow on" (click rapidly) to activate cheats like "Big Head Mode" or "Disco Floor."
*   **Konami Code:** Up, Up, Down, Down... you know the rest. Unlocks "God Mode" (or does it?).
*   **Flooble Clank:** A machine that does nothing but make a "Flooble" sound and a "Clank" sound. You can upgrade it to be louder.
*   **Philosopher's Stone:** Transmutes Lead into Gold, but mostly just complains about the price of reagents.
*   **NFT Collection:** A gallery of procedurally generated "Non-Fungible Toadstools" that you can't actually sell.
*   **Backseat Gamer:** A disembodied voice that criticizes your strategy ("You missed a spot", "My grandma plays faster").
*   **Interdimensional Customs:** Randomly stops your resource packets for "inspection."
*   **Reply All Disaster:** A simulated email storm that lags your UI with corporate buzzwords.
*   **Censored Pipe:** A pipe that is pixelated and beeps whenever resources flow through it.
*   **Recursive Review Loop:** A modal that asks you to review the review modal.

## 🎧 Audio Experience
*   **Procedural Soundtrack:** Generative ambient music that evolves with your network.
*   **ASMR Mode:** "Dump and Pleasant" sound design. Low-frequency thuds, warm hums, and zero high-pitched beeps.
*   **Audio Ducking:** The music politely lowers its volume when Gary speaks (or when you step on a wet floor).
*   **Interdimensional Radio:** A fully functional radio widget featuring:
    *   **Real Streams:** Direct integration with **Radio Garden** and **SomaFM** (Space Station, Drone Zone, etc.).
    *   **Synth Stations:** Procedurally generated stations (Pink Noise, Brown Noise) for pure focus.
    *   **Independent Volume:** Listen to the radio even when the main game is muted.
    *   **"Space?" Station:** Now fixed and broadcasting from the void.
    *   **Pyongyang FM:** Yes, you can stream the only and official North Korean radio station in-game. Don't ask why.

## 🛠 Technical Details
*   **Custom Engine:** Built from scratch in React + Canvas API.
*   **No Libraries:** (Almost) zero dependencies. Physics, particles, and audio synthesis are all hand-rolled.
*   **Robust Physics:** Fluid simulation now includes a "Warm-Up" phase on load to ensure instant pressure propagation, plus NaN safety checks and case-insensitive node handling.
*   **Save System:** Auto-saves every 5 seconds and immediately upon tab closure. Your progress is safe from the void.
*   **Spaghetti Code:** Intentionally authentic. (Gary's eye-tracking is now throttled to prevent recursive crashes, because even spaghetti has limits).

---

## 🐛 Known Issues & Performance
*   **Performance:** The simulation is heavy! If you experience lag, please try zooming in (less to render) or closing other browser tabs.
*   **Feedback:** I am aware of the performance bottlenecks and am actively working on them. If you have specific optimization tips, please let me know!

---

*Made with ❤️ (and Spite) by the Neon Mycelium Team.*
`;

const ReadmeModal = ({ forceOpen, onClose }) => {
    const [isOpen, setIsOpen] = useState(false);
    const { containerStyle, flashStyle, isVisible } = useCRTWindow(isOpen, { preset: 'STIFF' });

    useEffect(() => {
        const hasSeen = localStorage.getItem('hasSeenReadme');
        if (!hasSeen || forceOpen) {
            setIsOpen(true);
        }
    }, [forceOpen]);

    const handleClose = () => {
        setIsOpen(false);
        localStorage.setItem('hasSeenReadme', 'true');
        if (onClose) onClose();
    };

    if (!isVisible) return null;

    // Simple Markdown Parser
    const renderMarkdown = (text) => {
        return text.split('\n').map((line, index) => {
            if (line.startsWith('# ')) {
                return <h1 key={index} style={{ color: '#00FFFF', textShadow: '0 0 10px #00FFFF', marginTop: '20px' }}>{line.replace('# ', '')}</h1>;
            }
            if (line.startsWith('## ')) {
                return <h2 key={index} style={{ color: '#FF00FF', textShadow: '0 0 10px #FF00FF', marginTop: '15px', borderBottom: '1px solid #FF00FF' }}>{line.replace('## ', '')}</h2>;
            }
            if (line.startsWith('### ')) {
                return <h3 key={index} style={{ color: '#00FF00', marginTop: '10px' }}>{line.replace('### ', '')}</h3>;
            }
            if (line.startsWith('> [!TIP]')) {
                return null; // Skip the tip marker line, next lines will be handled
            }
            if (line.startsWith('> **PRO TIP:**')) {
                return (
                    <div key={index} style={{
                        border: '1px solid #FFFF00',
                        background: 'rgba(255, 255, 0, 0.1)',
                        padding: '10px',
                        margin: '10px 0',
                        color: '#FFFF00',
                        fontWeight: 'bold'
                    }}>
                        {line.replace('> ', '')}
                    </div>
                );
            }
            if (line.startsWith('*   ') || line.startsWith('-   ')) {
                const content = line.replace(/^[*|-]\s+/, '');
                const parts = content.split('**');
                return (
                    <li key={index} style={{ marginLeft: '20px', color: '#EEE', marginBottom: '5px' }}>
                        {parts.map((part, i) => i % 2 === 1 ? <strong key={i} style={{ color: '#FFFF00' }}>{part}</strong> : part)}
                    </li>
                );
            }
            if (line.startsWith('    *   ')) {
                const content = line.replace(/^\s+\*\s+/, '');
                const parts = content.split('**');
                return (
                    <li key={index} style={{ marginLeft: '40px', color: '#CCC', marginBottom: '3px', listStyleType: 'circle' }}>
                        {parts.map((part, i) => i % 2 === 1 ? <strong key={i} style={{ color: '#FFFF00' }}>{part}</strong> : part)}
                    </li>
                );
            }
            if (line.startsWith('> ')) {
                return <blockquote key={index} style={{ borderLeft: '4px solid #FF00FF', paddingLeft: '10px', fontStyle: 'italic', color: '#AAA' }}>{line.replace('> ', '')}</blockquote>;
            }
            if (line.trim() === '') {
                return <br key={index} />;
            }
            return <p key={index} style={{ marginBottom: '5px' }}>{line}</p>;
        });
    };

    return (
        <div style={{
            position: 'fixed',
            top: 0,
            left: 0,
            width: '100vw',
            height: '100vh',
            background: 'rgba(0,0,0,0.8)',
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            zIndex: 99999,
            pointerEvents: 'auto' // Ensure background captures clicks if needed, but mainly to allow child interaction
        }}>
            <div style={{
                ...containerStyle,
                display: isVisible ? 'flex' : 'none', // Use isVisible from hook
                width: '800px',
                height: '80vh',
                background: 'rgba(10, 5, 20, 0.95)',
                border: '2px solid #00FFFF',
                boxShadow: '0 0 30px rgba(0, 255, 255, 0.3)',
                flexDirection: 'column',
                padding: '20px',
                position: 'relative',
                pointerEvents: 'auto' // Explicitly enable pointer events
            }}>
                <div style={flashStyle} />

                {/* Header */}
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid #00FFFF', paddingBottom: '10px', marginBottom: '10px', flexShrink: 0 }}>
                    <span style={{ fontFamily: 'monospace', color: '#00FFFF', fontSize: '18px' }}>MANUAL.MD</span>
                    <SquishyButton onClick={handleClose} style={{ background: '#FF0000', color: 'white', padding: '5px 10px' }}>
                        CLOSE [X]
                    </SquishyButton>
                </div>

                {/* Content */}
                <div
                    onWheel={(e) => e.stopPropagation()} // Stop propagation to game canvas
                    style={{
                        flex: 1,
                        overflowY: 'scroll', // Force scrollbar
                        fontFamily: 'monospace',
                        paddingRight: '10px',
                        lineHeight: '1.5',
                        minHeight: '0',
                        pointerEvents: 'auto', // Explicitly enable
                        position: 'relative',
                        zIndex: 2
                    }}
                >
                    {renderMarkdown(README_CONTENT)}
                </div>

                {/* Footer */}
                <div style={{ marginTop: '10px', textAlign: 'center', fontSize: '10px', color: '#666', flexShrink: 0 }}>
                    SCROLL TO READ THE TRUTH
                </div>
            </div>
        </div>
    );
};

export default ReadmeModal;
